version: "3.8"
services:
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile.postgres
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "12345:5432"

    firebase:
        container_name: firebase
        build:
            context: ./docker/firebase
            dockerfile: Dockerfile.firebase
        volumes:
            - ./package.json:/usr/src/app/package.json
            - ./node_modules/:/usr/src/app/node_modules
            - ./.firebaserc:/usr/src/app/.firebaserc
            - ./firebase.json:/usr/src/app/firebase.json
        ports:
            - 9099:9099 # Firebase Authentication
            - 8080:8080 # Cloud Firestore
            - 5002:5002 # Firebase Hosting
            - 9199:9199 # Cloud Storage
            - 4000:4000 # Emulator Suite UI
            - 9150:9150 # Firestore Emulator UI websocket
        working_dir: /usr/src/app
        tty: true
        environment:
            - FIREBASE_TOKEN=${FIREBASE_TOKEN}
volumes:
    postgres_data:
