FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    curl \
    openjdk-17-jdk \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools

CMD ["firebase", "emulators:start", "--project", "demo-project"]